/* generated by unplugin-react-components */
export {}
declare global{
	const App: typeof import('./src/App')['default']
	const Dashboard: typeof import('./src/layouts/dashboard')['default']
	const Home: typeof import('./src/layouts/home')['default']
	const NotFoundPage: typeof import('./src/pages/[...all]')['default']
	const Button: typeof import('./src/components/core/Button')['default']
	const Card: typeof import('./src/components/core/Card')['default']
	const Footer: typeof import('./src/components/layout/Footer')['default']
}